import type { PatternResult } from "./types";
import { drawPattern } from "./render/draw";
import { rgbCss } from "./core/colorSpace";

export interface EditorLabels { title:string; brush:string; erase:string; pan:string; undo:string; redo:string; fit:string; export:string; done:string }
type CellChange={index:number;color:number;empty:number};

export function openPatternEditor(pattern:PatternResult,labels:EditorLabels,onExport:()=>Promise<unknown>,onClose:()=>void):void {
  const root=document.createElement("div");root.className="editor-overlay";root.innerHTML=`<div class="editor-shell"><div class="editor-head"><strong>${labels.title}</strong><div class="editor-actions"><button data-tool="brush" class="active">✎ ${labels.brush}</button><button data-tool="erase">⌫ ${labels.erase}</button><button data-tool="pan">✥ ${labels.pan}</button><button id="editorUndo" disabled>↶ ${labels.undo}</button><button id="editorRedo" disabled>↷ ${labels.redo}</button><button id="editorZoomOut">−</button><button id="editorFit">⊡ ${labels.fit}</button><button id="editorZoomIn">＋</button><button id="editorExport" class="primary">${labels.export}</button><button id="editorDone">${labels.done}</button></div></div><div class="editor-body"><div class="editor-palette"></div><div class="editor-stage"><canvas></canvas></div></div></div>`;document.body.append(root);
  const canvas=root.querySelector("canvas")!,stage=root.querySelector<HTMLElement>(".editor-stage")!,palette=root.querySelector<HTMLElement>(".editor-palette")!;
  const used=[...new Set([...pattern.colorIndices].filter((_,i)=>!pattern.empty[i]))];let selected=used[0]??0,tool:"brush"|"erase"|"pan"="brush",zoom=1,drawing=false,panning=false,startX=0,startY=0,scrollX=0,scrollY=0,current=new Map<number,CellChange>();const undo:CellChange[][]=[],redo:CellChange[][]=[];
  const cellSize=Math.max(4,Math.min(24,Math.floor(8192/Math.max(pattern.width,pattern.height))));canvas.width=pattern.width*cellSize;canvas.height=pattern.height*cellSize;
  const updateButtons=()=>{(root.querySelector("#editorUndo") as HTMLButtonElement).disabled=!undo.length;(root.querySelector("#editorRedo") as HTMLButtonElement).disabled=!redo.length};
  const render=()=>{drawPattern(canvas.getContext("2d")!,pattern,{cellSize,grid:true,labels:true,labelMode:"code",round:false,guides:true});canvas.style.width=`${Math.round(canvas.width*zoom)}px`;canvas.style.height=`${Math.round(canvas.height*zoom)}px`};
  const setZoom=(value:number)=>{zoom=Math.max(.05,Math.min(8,value));render()};
  const fit=()=>setZoom(Math.min(1,(stage.clientWidth-32)/canvas.width,(stage.clientHeight-32)/canvas.height));
  const choose=(index:number)=>{selected=index;tool="brush";root.querySelectorAll("[data-tool]").forEach(el=>el.classList.toggle("active",(el as HTMLElement).dataset.tool==="brush"));palette.querySelectorAll("button").forEach(el=>el.classList.toggle("active",Number(el.dataset.color)===index))};
  palette.innerHTML=used.map(index=>{const color=pattern.palette[index];return `<button data-color="${index}" title="${color.code}"><i style="background:${rgbCss(color.rgb)}"></i><b>${color.code}</b></button>`}).join("");palette.querySelectorAll<HTMLButtonElement>("button").forEach(button=>button.onclick=()=>choose(Number(button.dataset.color)));choose(selected);
  const cellAt=(event:PointerEvent)=>{const rect=canvas.getBoundingClientRect(),x=Math.floor((event.clientX-rect.left)/rect.width*pattern.width),y=Math.floor((event.clientY-rect.top)/rect.height*pattern.height);return x>=0&&y>=0&&x<pattern.width&&y<pattern.height?y*pattern.width+x:-1};
  const paint=(index:number)=>{if(index<0)return;if(!current.has(index))current.set(index,{index,color:pattern.colorIndices[index],empty:pattern.empty[index]});if(tool==="erase")pattern.empty[index]=1;else{pattern.empty[index]=0;pattern.colorIndices[index]=selected}render()};
  canvas.onpointerdown=event=>{if(tool==="pan"){panning=true;startX=event.clientX;startY=event.clientY;scrollX=stage.scrollLeft;scrollY=stage.scrollTop}else{drawing=true;current=new Map;paint(cellAt(event))}canvas.setPointerCapture(event.pointerId)};
  canvas.onpointermove=event=>{if(panning){stage.scrollLeft=scrollX-(event.clientX-startX);stage.scrollTop=scrollY-(event.clientY-startY)}else if(drawing)paint(cellAt(event))};
  const finish=()=>{if(drawing&&current.size){undo.push([...current.values()]);redo.length=0;updateButtons()}drawing=false;panning=false};canvas.onpointerup=canvas.onpointercancel=finish;
  root.querySelectorAll<HTMLButtonElement>("[data-tool]").forEach(button=>button.onclick=()=>{tool=button.dataset.tool as typeof tool;root.querySelectorAll("[data-tool]").forEach(el=>el.classList.toggle("active",el===button))});
  const restore=(changes:CellChange[])=>{const inverse=changes.map(({index})=>({index,color:pattern.colorIndices[index],empty:pattern.empty[index]}));changes.forEach(change=>{pattern.colorIndices[change.index]=change.color;pattern.empty[change.index]=change.empty});render();return inverse};
  (root.querySelector("#editorUndo") as HTMLButtonElement).onclick=()=>{const changes=undo.pop();if(changes)redo.push(restore(changes));updateButtons()};(root.querySelector("#editorRedo") as HTMLButtonElement).onclick=()=>{const changes=redo.pop();if(changes)undo.push(restore(changes));updateButtons()};
  (root.querySelector("#editorZoomOut") as HTMLButtonElement).onclick=()=>setZoom(zoom/1.25);(root.querySelector("#editorFit") as HTMLButtonElement).onclick=fit;(root.querySelector("#editorZoomIn") as HTMLButtonElement).onclick=()=>setZoom(zoom*1.25);(root.querySelector("#editorExport") as HTMLButtonElement).onclick=()=>void onExport();stage.onwheel=event=>{event.preventDefault();setZoom(zoom*(event.deltaY<0?1.12:1/1.12))};
  const close=()=>{root.remove();onClose()};(root.querySelector("#editorDone") as HTMLButtonElement).onclick=close;root.onkeydown=event=>{if(event.key==="Escape")close()};root.tabIndex=-1;root.focus();render();requestAnimationFrame(fit);
}
