export type Locale = "zh-CN" | "en" | "ja" | "de" | "ko" | "zh-TW";

export const localeNames: Record<Locale, string> = {
  "zh-CN": "简体中文", en: "English", ja: "日本語", de: "Deutsch", ko: "한국어", "zh-TW": "繁體中文"
};

const en = {
  tagline:"PRIVATE · LOCAL · PRACTICAL", subtitle:"Turn an image into a buildable fuse bead chart—nothing leaves your browser.", local:"Local processing only",
  source:"Source image", drop:"Drop an image or browse", formats:"JPG, PNG or WebP · processed locally", noFile:"No image selected",
  gridCrop:"Grid & crop", width:"Width", height:"Height", imageFit:"Image fit", cover:"Cover · crop edges", contain:"Contain · add margin", stretch:"Stretch",
  removeBg:"Smart outer background removal", removeBgHint:"Conservative: detects similar corner colors and removes only edge-connected background",
  matching:"Color matching", palette:"Bead palette", mard:"MARD · common shop codes (221)", hama:"Hama · community measured (46)", sourceNeeded:"data source needed", maxColors:"Maximum colors", auto:"Auto", unlimited:"Unlimited", best:"Best match", practical:"Practical", practicalHint:"Practical mode merges isolated near-colors while preserving visible edges.",
  display:"Chart display", grid:"Grid", labels:"Labels", guides:"5 / 10 grid guides", shortSymbols:"Short symbols", codes:"Color codes", beads:"Beads", round:"Round", square:"Square",
  original:"Original", preview:"Bead preview", chart:"Chart", addImage:"Add an image to begin", appear:"Your pattern will appear here", tryImage:"Try a clear photo, illustration, logo or pixel art.", colors:"Colors", exportPreview:"Color image", exportChart:"Export chart", usageEmpty:"Color usage will appear after conversion.", matched:"Matched with CIEDE2000", processing:"Processing…", tooLarge:"Large grids can take time and memory.",
  language:"Language", theme:"Theme", system:"System", light:"Light", dark:"Dark", openSource:"Open source · MIT License", variance:"Color appearance varies by screen, lighting and manufacturing batch.", invalid:"Please choose a JPG, PNG or WebP image.", decodeError:"This image could not be decoded.", shareTitle:"Bead pattern", saveHint:"Choose “Save Image” in the share sheet.",
  lock:"Lock source aspect ratio", zoomIn:"Zoom in", zoomOut:"Zoom out", fitView:"Fit to view"
};
type Key = keyof typeof en;
const zhCN: Record<Key,string> = {
  tagline:"隐私 · 本地 · 实用",subtitle:"把图片转换成真正可以制作的拼豆图纸——图片不会离开你的浏览器。",local:"仅在本地处理",source:"原始图片",drop:"拖入图片或点击选择",formats:"JPG、PNG 或 WebP · 仅本地处理",noFile:"尚未选择图片",gridCrop:"网格与裁切",width:"宽度",height:"高度",imageFit:"图片适配",cover:"覆盖 · 裁切边缘",contain:"包含 · 保留留白",stretch:"拉伸",removeBg:"智能移除外围背景",removeBgHint:"保守识别四角近似背景色，仅移除与图片边缘相连的区域",matching:"颜色匹配",palette:"拼豆色卡",mard:"MARD · 店铺常用色号（221 色）",hama:"Hama · 社区测量（46 色）",sourceNeeded:"待补可靠数据",maxColors:"最多颜色数",auto:"自动",unlimited:"不限制",best:"最高拟合",practical:"实用拼豆",practicalHint:"实用模式会合并孤立的相近颜色，同时保留明显边缘。",display:"图纸显示",grid:"网格",labels:"标记",guides:"5 / 10 格分区线",shortSymbols:"短字母",codes:"色号",beads:"拼豆",round:"圆形",square:"方形",original:"原图",preview:"拼豆预览",chart:"图纸",addImage:"上传图片后开始",appear:"拼豆图将在这里显示",tryImage:"建议使用清晰照片、插画、Logo 或像素画。",colors:"颜色",exportPreview:"彩图",exportChart:"导出图纸",usageEmpty:"转换后将在这里显示颜色用量。",matched:"已使用 CIEDE2000 匹配",processing:"正在处理…",tooLarge:"大尺寸网格可能消耗较多时间和内存。",language:"语言",theme:"主题",system:"跟随系统",light:"浅色",dark:"深色",openSource:"开源项目 · MIT 协议",variance:"颜色会因屏幕、光线和生产批次而有差异。",invalid:"请选择 JPG、PNG 或 WebP 图片。",decodeError:"无法解析这张图片。",shareTitle:"拼豆图纸",saveHint:"请在系统分享菜单中选择“存储图像”。",lock:"锁定原图宽高比",zoomIn:"放大",zoomOut:"缩小",fitView:"适应窗口"
};
const zhTW: Record<Key,string> = {...zhCN,subtitle:"把圖片轉換成真正可以製作的拼豆圖紙——圖片不會離開你的瀏覽器。",local:"僅在本機處理",source:"原始圖片",drop:"拖入圖片或點擊選擇",noFile:"尚未選擇圖片",gridCrop:"網格與裁切",width:"寬度",height:"高度",imageFit:"圖片適配",removeBg:"智慧移除外圍背景",removeBgHint:"保守辨識四角近似背景色，僅移除與圖片邊緣相連的區域",matching:"顏色匹配",palette:"拼豆色卡",maxColors:"最多顏色數",auto:"自動",best:"最高擬合",practical:"實用拼豆",display:"圖紙顯示",labels:"標記",codes:"色號",original:"原圖",preview:"拼豆預覽",chart:"圖紙",addImage:"上傳圖片後開始",appear:"拼豆圖將在這裡顯示",colors:"顏色",exportPreview:"匯出彩色 PNG",exportChart:"匯出施工圖 PNG",usageEmpty:"轉換後將在這裡顯示顏色用量。",processing:"正在處理…",language:"語言",theme:"主題",system:"跟隨系統",light:"淺色",dark:"深色",saveHint:"請在系統分享選單中選擇「儲存影像」。"};
const ja: Record<Key,string> = {...en,subtitle:"画像を実際に作れるビーズ図案へ。画像はブラウザの外へ送信されません。",local:"端末内だけで処理",source:"元画像",drop:"画像をドロップまたは選択",noFile:"画像が選択されていません",gridCrop:"グリッドと切り抜き",width:"幅",height:"高さ",imageFit:"画像フィット",removeBg:"外側の背景を自動除去",removeBgHint:"四隅の近似色を検出し、端につながる背景だけを除去",matching:"カラーマッチング",palette:"ビーズパレット",maxColors:"最大色数",auto:"自動",unlimited:"無制限",best:"最高精度",practical:"作りやすさ優先",display:"図案表示",grid:"グリッド",labels:"記号",beads:"ビーズ",original:"元画像",preview:"ビーズプレビュー",chart:"図案",addImage:"画像を追加してください",appear:"ここに図案が表示されます",colors:"色",exportPreview:"カラー PNG を出力",exportChart:"図案 PNG を出力",usageEmpty:"変換後に使用色が表示されます。",processing:"処理中…",language:"言語",theme:"テーマ",system:"システム",light:"ライト",dark:"ダーク",saveHint:"共有シートで「画像を保存」を選択してください。"};
const de: Record<Key,string> = {...en,subtitle:"Verwandle Bilder lokal im Browser in umsetzbare Bügelperlen-Vorlagen.",local:"Nur lokale Verarbeitung",source:"Quellbild",drop:"Bild ablegen oder auswählen",noFile:"Kein Bild ausgewählt",gridCrop:"Raster & Zuschnitt",width:"Breite",height:"Höhe",imageFit:"Bildanpassung",removeBg:"Hintergrund am Rand erkennen",removeBgHint:"Erkennt ähnliche Eckfarben und entfernt nur randverbundene Bereiche",matching:"Farbabgleich",palette:"Perlenpalette",maxColors:"Maximale Farben",auto:"Automatisch",unlimited:"Unbegrenzt",best:"Beste Übereinstimmung",practical:"Praktisch",display:"Vorlagenanzeige",grid:"Raster",labels:"Markierungen",beads:"Perlen",original:"Original",preview:"Perlenvorschau",chart:"Vorlage",addImage:"Bild hinzufügen",appear:"Deine Vorlage erscheint hier",colors:"Farben",exportPreview:"Farb-PNG exportieren",exportChart:"Vorlagen-PNG exportieren",usageEmpty:"Nach der Umwandlung erscheint hier der Farbverbrauch.",processing:"Verarbeitung…",language:"Sprache",theme:"Darstellung",system:"System",light:"Hell",dark:"Dunkel",saveHint:"Wähle im Teilen-Menü „Bild sichern“ aus."};
const ko: Record<Key,string> = {...en,subtitle:"이미지를 실제로 만들 수 있는 비즈 도안으로 변환합니다. 이미지는 브라우저를 벗어나지 않습니다.",local:"기기에서만 처리",source:"원본 이미지",drop:"이미지를 놓거나 선택",noFile:"선택한 이미지 없음",gridCrop:"격자 및 자르기",width:"너비",height:"높이",imageFit:"이미지 맞춤",removeBg:"바깥 배경 자동 제거",removeBgHint:"모서리의 유사한 색을 감지해 가장자리에 연결된 배경만 제거",matching:"색상 매칭",palette:"비즈 팔레트",maxColors:"최대 색상 수",auto:"자동",unlimited:"제한 없음",best:"최고 일치",practical:"실용 모드",display:"도안 표시",grid:"격자",labels:"표시",beads:"비즈",original:"원본",preview:"비즈 미리보기",chart:"도안",addImage:"이미지를 추가하세요",appear:"여기에 도안이 표시됩니다",colors:"색상",exportPreview:"컬러 PNG 내보내기",exportChart:"도안 PNG 내보내기",usageEmpty:"변환 후 색상 사용량이 표시됩니다.",processing:"처리 중…",language:"언어",theme:"테마",system:"시스템",light:"라이트",dark:"다크",saveHint:"공유 메뉴에서 ‘이미지 저장’을 선택하세요."};

const dictionaries: Record<Locale,Record<Key,string>> = {"zh-CN":zhCN,en,ja,de,ko,"zh-TW":zhTW};
export const t = (locale: Locale, key: Key): string => dictionaries[locale][key];
